### ISSUE TITLE
Crash while loading game. Crafting Material - no such field error.

### ISSUE THREAD

**Issue by Zarepheth** [SilentChaos512/SGExtraParts#12]
### Versions

Minecraft Version: 1.12.2
Extra Parts Version: 1.4.4-42
Silent's Gems Version: 2.8.3-295
Silent Lib Version: 3.0.3-148

### Expected behavior

- Games starts without error. 
  (_World loads without error. Game plays without error._)

### Actual behaviour

- Crash during game startup.
Paste.ee of full log file: [https://paste.ee/p/QiNQX](https://paste.ee/p/QiNQX)

Error portion of log file:
```
Description: Initializing game

java.lang.NoSuchFieldError: craftingMaterial
	at net.silentchaos512.sgextraparts.lib.EnumPartExtreme.getCraftingStack(EnumPartExtreme.java:70)
	at net.silentchaos512.sgextraparts.lib.ToolPartSGEP.<init>(ToolPartSGEP.java:25)
	at net.silentchaos512.sgextraparts.lib.EnumPartExtreme.registerToolParts(EnumPartExtreme.java:96)
	at net.silentchaos512.sgextraparts.init.ModItems.registerAll(ModItems.java:24)
	at net.silentchaos512.lib.registry.SRegistry$EventHandler.runRegistrationHandlerIfPresent(SRegistry.java:575)
	at net.silentchaos512.lib.registry.SRegistry$EventHandler.registerItems(SRegistry.java:585)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_214_EventHandler_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:755)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

### Steps to reproduce the problem

1. Start the Minecraft.
2. Wait as game loads.
3. In a few minutes, the game crashes.

**Comment by SilentChaos512** [comment]
Uploaded version 1.4.5 of Extra Parts a little while ago, just waiting for the file to be approved.
